### ISSUE TITLE
bool field with default of True actually defaults to False when using QueryDict

### ISSUE THREAD

**Issue by ses4j** [oxan/djangorestframework-dataclasses#61]
If you pass a QueryDict to a serializer (such as request.GET), the bool somehow loses it's default value.

Demonstration:
```
from dataclasses import dataclass
from rest_framework_dataclasses.serializers import DataclassSerializer


@dataclass
class MyClass:
    my_bool: bool = True


class MySerializer(DataclassSerializer):
    class Meta:
        dataclass = MyClass


from django.http import QueryDict
from django.conf import settings

settings.configure()
s = MySerializer(data=QueryDict(encoding='utf8'))
assert s.is_valid()
assert s.data['my_bool'] is True, "this should be true but is false!"
```

**Comment by oxan** [comment]
Which version are you using? If I try this in the REPL, it seems to work as expected:
```
>>> from dataclasses import dataclass
>>> from rest_framework_dataclasses.serializers import DataclassSerializer
>>> @dataclass
... class MyClass:
...     my_bool: bool = True
... 
>>> class MySerializer(DataclassSerializer):
...     class Meta:
...         dataclass = MyClass
... 
>>> from django.http import QueryDict
>>> from django.conf import settings
>>> settings.configure()
>>> s = MySerializer(data=QueryDict(encoding='utf8'))
>>> s.is_valid()
True
>>> s.data
{'my_bool': False}
```

**Comment by oxan** [comment]
The root cause is this check, which triggers for a `QueryDict` but doesn't for a regular one.
https://github.com/encode/django-rest-framework/blob/54d52c66fd221e9ff86d8b428c6c0178c0501606/rest_framework/fields.py#L422-L428

It seems that DRF assumes a missing value in a `QueryDict` is `None` or `False`. You can workaround it by setting the `partial=True` option, to only consider fields that are present.

**Comment by ses4j** [comment]
Thanks!

**Comment by ses4j** [comment]
Ah, interesting.  That's true, though I then lose validation on required params.
